apiVersion: v1
kind: Service
metadata:
  name: opportunity-service
  namespace: opportunity-portal
spec:
  selector:
    app: opportunity-service
  ports:
    - port: 80
      targetPort: 8080
  type: ClusterIP
