apiVersion: v1
kind: Service
metadata:
  name: web-frontend
  namespace: opportunity-portal
spec:
  selector:
    app: web-frontend
  ports:
    - port: 80
      targetPort: 5173
  type: LoadBalancer
