apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: opportunity-portal
  namespace: argocd
spec:
  project: default
  source:
    repoURL: "https://github.com/vaibhavmani928/opportunity-portal-gitops"
    targetRevision: HEAD
    path: overlays/prod
  destination:
    server: https://kubernetes.default.svc
    namespace: opportunity-portal
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
